server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          # if using local directory:
          #uri: file://${user.home}/safe-map-backend/config-repo
          # or remote git repo:
          uri: https://github.com/Erenriquezp/safe-map-backend
          default-label: master
management:
  endpoints:
    web:
      exposure:
        include: "*"
