server:
  port: 8082

spring:
  application:
    name: safeplace-service
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      uri: mongodb://localhost:27017/safemap_places

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  info:
    env:
      enabled: true

info:
  app:
    name: safeplace-service
    version: 1.0.0
    description: Places service for SafeMap